apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-app
  labels:
    app: backend
    type: development
spec:
  selector:
    app: backend
  template:
    metadata:
      name: my-app
      labels:
        app: backend
    spec:
      containers:
      - name: alpha
        image: nginx
  replicas: 5
