apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: main-container
    image: busybox:stable
    command: ['sh', '-c', 'echo "i am learning kubernetes." > /output/data.txt; while true; do sleep 3600; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /output

  - name: side-car
    image: busybox:stable
    command: ['sh', '-c', 'while true; do cat /input/data.txt; sleep 3600; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /input

  volumes:
  - name: shared-volume
    emptyDir: {}
