apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-env
      color: blue
  template:
    metadata:
      labels:
        app: bg-env
        color: blue
    spec:
      containers:
      - name: bluegreen
        image: linuxacademycontent/ckad-nginx:blue
        ports:
        - containerPort: 80
