apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: my-app
    tier: backend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: roll-app  
  template:
    metadata:
      labels:
        app: roll-app
    spec:
      containers:
      - name: nginx-containers
        image: nginx:1.22
