apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-object
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        -  containerPort: 80

