apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: production
    app: web-app
  name: my-prod-dev
  namespace: default
spec:
  containers:
  - name: prod-app 
    image: kodekloud/webapp-delayed-start
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: APP_DELAY
      value: "300"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    livenessProbe:
      httpGet:
        path: /live
        port: 8080  
      periodSeconds: 2   #after every 3 second check my pod
      initialDelaySeconds: 130
