apiVersion: v1
kind: Service 
metadata:
  name: dashboard-svc
  labels:
    app: dashboard-s
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboard  # Make sure this matches the Pod labels
  type: NodePort