apiVersion: v1
kind: Pod
metadata:
  name: pod-res-check
  labels:
    app: resources
spec:
  containers:
  - image: polinux/stress
    name: memory-check
    command:
    - stress 
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "15M"
    - "--vm-hang"
    - "1"
    resources:
      limits:
        memory: 10Gi
      requests:
        memory: 5Gi
  