apiVersion: v1
kind: Pod
metadata:
  name: pod-res
  labels:
    app: resources
spec:
  containers:
  - image: ubuntu
    name: ubuntu-cont
    command:
    - sleep
    - "3600"
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1