apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: default
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: paswrd
    ports:
    - containerPort: 3306
      protocol: TCP