apiVersion: v1
kind: Pod
metadata:
  name: cont-pod1
spec:
  securityContext:
    runAsUser: 1006
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 1002
  
  - name: side-car
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]