apiVersion: v1
kind: Pod
metadata:
  name: cont-sec1
spec:
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 1002