apiVersion: v1
kind: ResourceQuota
metadata: 
  name: resources-quota
  namespace: myspace
spec:
  hard:
   pods: "2"
   requests.cpu: "2"
   requests.memory: 2Gi
   limits.cpu: "2"
   limits.memory: 3Gi