apiVersion: v1
kind: Pod
metadata:
  name: webe-pod
  namespace: default
  labels:
    app: config
    version: prod
spec:
  containers:
  - name: alpha
    image: kodekloud/webapp-color
    envFrom:
    - configMapRef:
        name: web-config