apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alnafi
  name: alnafi
spec:
  replicas: 6
  selector:
    matchLabels:
      app: alnafi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alnafi
    spec:
      containers:
      - image: nginx
        name: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: platform
                operator: NotIn
                values:
                - aws
