apiVersion: v1
kind: Pod
metadata:
  name: web-app
  namespace: default
  labels:
    name: web-app  # Ensure this label matches the selector in the service
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: web-app