apiVersion: v1
kind: Pod
metadata:
  name: web-app1
  namespace: default
  labels:
    name: web-app
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: web-app
    envFrom:
    - secretRef:
        name: db-secret
    